apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: latest
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: latest
  template:
    metadata:
      labels:
        app: latest
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.container.portName }}
              containerPort: {{ .Values.container.portValue }}
              protocol: {{ .Values.container.portProtocol }}
          env:
            - name: REACT_APP_DOMAIN_API_SDK
              value: stg.sota-data-api.sotaicg.com/
            - name: REACT_APP_CHUNK_SIZE_MB
              value: "100"
            - name: REACT_APP_GOOGLE_CLIENT_ID
              value: http://81963526024-m0rt10khegk1fici68g7punu1spuqnhs.apps.googleusercontent.com/
            - name: REACT_APP_API_URL
              value: https://stg.sota-data-api.sotaicg.com/api/v1

